# Generated by Django 5.0.3 on 2024-10-22 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_booking_case_type_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
